defaults:
  - eeg_model: 1D-ResNet-18
  - mri_model: 3D-ResNet-18
  - _self_
#defaults:
#  - eeg_model: MST-eeg
#  - mri_model: MST-mri
#  - _self_

_target_: models.multimodal.EMMNet

############### MODEL ARCHITECTURE

concat_dim: 256
output_length: 2
fc_stages: 1
activation: gelu #mish, gelu, relu
mri_norm_type: 'min_max' # z_score or min_max
fusion: 'concat'  # 'attention'
mri_freeze: false
eeg_freeze: true

minibatch_4090: 8