defaults:
  - eeg_model: 1D-ResNeXt-50
  - mri_model: 3D-ResNet-18
  - _self_

_target_: models.multimodal.EMMNet

############### MODEL ARCHITECTURE
use_age: no
concat_dim: 128
output_length: 3
fc_stages: 1
activation: gelu #mish, gelu, relu
mri_norm_type: 'z_score'
eeg_freeze: false

minibatch_4090: 16