run_mode: test

# reproducibility
seed: 0

# load Pretrained weight
load_pretrained: Exp/mvv6l6bg


# test option
test_accuracy_repeat: 100
Medcam: false

# regularization
criterion: cross-entropy
weight_decay: 0.01
mixup: 0.0

# log
num_history: 500
save_model: false

# wandb
use_wandb: false
draw_result: true
watch_model: false

# GPU
ddp: false
# device: ???  automatically decided during runtime
# ddp_size: ???  automatically decided during runtime