run_mode: train
load_pretrained: True

# reproducibility
seed: 0

# Training iteration
base_lr: 1.33e-4
search_lr: false
search_multiplier: 1.0
lr_scheduler_type: cosine_decay_with_warmup_half # constant_with_decay
warmup_ratio: 0.05
warmup_min: 3000
total_samples: 2000
# iterations: ???  # automatically decided during runtime

# regularization
criterion: cross-entropy
weight_decay: 4.71e-02
mixup: 0.0  # must set to be 0

# log
num_history: 500
save_model: true

# wandb
use_wandb: false
draw_result: true
watch_model: false

# GPU
ddp: true
# device: ???  automatically decided during runtime
# ddp_size: ???  automatically decided during runtime