defaults:
  - data: cauemm-abnormal
#  - trainer: base_test
#  - trainer: tiny-train
#  - trainer: base_train
  - trainer: fine_tune
  - model: multi-modal
  - _self_

hydra:
  run:
    dir: local/hydra/${now:%Y-%m-%d}/${now:%H-%M-%S}

