defaults:
  - data: cauemm-abnormal
  - trainer: base_test
  - model: 3D-ResNet-18
  - _self_

#defaults:
#  - data: cauemm-abnormal
#  - trainer: base_test
#  - model: multi-modal
#  - _self_

hydra:
  run:
    dir: local/hydra/${now:%Y-%m-%d}/${now:%H-%M-%S}

