defaults:
  - base_model
  - 1D-ResNet-Base
  - _self_

model: 1D-ResNeXt-50
conv_layers: [3, 4, 6, 3]
block: bottleneck
groups: 32
use_age: conv
width_per_group: 4
activation: gelu
load_pretrained: CEEDNet/1D-ResNeXt-50