defaults:
  - base_model
  - _self_

_target_: models.simple_cnn_3d.Simple3DCNN
model: Simple3DCNN

in_channels: 1
out_dims: ${concat_dim}
fc_stages: 1
image_size: 128
base_channels: 4
activation: relu
minibatch_4090: 32